/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CitySlugRouteImport } from './routes/$citySlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitySlugArticleSlugRouteImport } from './routes/$citySlug.$articleSlug'

const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/$citySlug',
  path: '/$citySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugArticleSlugRoute = CitySlugArticleSlugRouteImport.update({
  id: '/$articleSlug',
  path: '/$articleSlug',
  getParentRoute: () => CitySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/disclosure': typeof DisclosureRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/$citySlug/$articleSlug': typeof CitySlugArticleSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/disclosure': typeof DisclosureRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/$citySlug/$articleSlug': typeof CitySlugArticleSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$citySlug': typeof CitySlugRouteWithChildren
  '/about': typeof AboutRoute
  '/cookies': typeof CookiesRoute
  '/disclosure': typeof DisclosureRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/$citySlug/$articleSlug': typeof CitySlugArticleSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$citySlug'
    | '/about'
    | '/cookies'
    | '/disclosure'
    | '/integritetspolicy'
    | '/$citySlug/$articleSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$citySlug'
    | '/about'
    | '/cookies'
    | '/disclosure'
    | '/integritetspolicy'
    | '/$citySlug/$articleSlug'
  id:
    | '__root__'
    | '/'
    | '/$citySlug'
    | '/about'
    | '/cookies'
    | '/disclosure'
    | '/integritetspolicy'
    | '/$citySlug/$articleSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitySlugRoute: typeof CitySlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  CookiesRoute: typeof CookiesRoute
  DisclosureRoute: typeof DisclosureRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug': {
      id: '/$citySlug'
      path: '/$citySlug'
      fullPath: '/$citySlug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$citySlug/$articleSlug': {
      id: '/$citySlug/$articleSlug'
      path: '/$articleSlug'
      fullPath: '/$citySlug/$articleSlug'
      preLoaderRoute: typeof CitySlugArticleSlugRouteImport
      parentRoute: typeof CitySlugRoute
    }
  }
}

interface CitySlugRouteChildren {
  CitySlugArticleSlugRoute: typeof CitySlugArticleSlugRoute
}

const CitySlugRouteChildren: CitySlugRouteChildren = {
  CitySlugArticleSlugRoute: CitySlugArticleSlugRoute,
}

const CitySlugRouteWithChildren = CitySlugRoute._addFileChildren(
  CitySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitySlugRoute: CitySlugRouteWithChildren,
  AboutRoute: AboutRoute,
  CookiesRoute: CookiesRoute,
  DisclosureRoute: DisclosureRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
